// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aufgcimxlcypuebbgbpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1ZmdjaW14bGN5cHVlYmJnYnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTA3MjcsImV4cCI6MjA2MjAyNjcyN30.e8RhOCtdh0Jq6cyIjhYVX33gDYtf6hKvsUR5qC6UgSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);